// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6tti4LjEtmYDOcdlgCjp1j4ihd3vGSoQ',
    appId: '1:504348983116:web:97957032046c2cefe019e9',
    messagingSenderId: '504348983116',
    projectId: 'hospital-e13e4',
    authDomain: 'hospital-e13e4.firebaseapp.com',
    storageBucket: 'hospital-e13e4.appspot.com',
    measurementId: 'G-64NVY7FW8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx22nlZLZqYWDwPh1A2J0C-boRFi8vbM4',
    appId: '1:504348983116:android:40a9af9a4947b694e019e9',
    messagingSenderId: '504348983116',
    projectId: 'hospital-e13e4',
    storageBucket: 'hospital-e13e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFuNefemVHGsHsSqXqbeLcrRwk3QKsN4A',
    appId: '1:504348983116:ios:8c84eb62da18741be019e9',
    messagingSenderId: '504348983116',
    projectId: 'hospital-e13e4',
    storageBucket: 'hospital-e13e4.appspot.com',
    iosClientId: '504348983116-vt32u4onmfe8n5j3010552p27b9slosl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFuNefemVHGsHsSqXqbeLcrRwk3QKsN4A',
    appId: '1:504348983116:ios:8c84eb62da18741be019e9',
    messagingSenderId: '504348983116',
    projectId: 'hospital-e13e4',
    storageBucket: 'hospital-e13e4.appspot.com',
    iosClientId: '504348983116-vt32u4onmfe8n5j3010552p27b9slosl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospital',
  );
}
